# Generated by Django 3.2.3 on 2022-12-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20221210_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fno-image-available&psig=AOvVaw35LvTbizKSyZNRhAnjDL-h&ust=1670775821403000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCMjx7Iy77_sCFQAAAAAdAAAAABAE'),
        ),
    ]
